# 唯一markdown文件路径
unique_md_filepath = "D:\\GPrjs\\cpp\\markdown\\do.md"
#
output_filepath = "D:\\GPrjs\\cpp\\output"
# 是否使用代理来打开网页，1=使用，2=不使用
use_proxy = 2
# 代理使用的协议：http/https/socks4/socks5
proxy_scheme = "https"
# 代理服务器的主机名
proxy_host = ""
# 代理服务器的端口
proxy_port = 1235
# 代理服务器的用户名
proxy_username = ""
# 代理服务器的用户密码
proxy_password = ""

# 间隔测试时间：单位为秒
interval_second = 5
# 浏览器宽度
browser_width = 1200
# 浏览器高度
browser_height = 1500
